name: pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 'v14.15.0'
      - name: install
        run: yarn install --frozen-lockfile
      - name: export
        run: yarn export
        env:
          CI: true
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./docs